#!/bin/sh
# a really simplified version of git-version-gen

VERSION_FILE=$1

if [ -n "$VERSION_FILE" ] && [ -f "$VERSION_FILE" ]; then
	cat "$VERSION_FILE"
	exit $?
fi

echo "$(git describe --abbrev=4 --tags '--match=osmo-epdg-[0-9]*\.[0-9]*\.[0-9a-z]*' 'HEAD' | sed 's/osmo-epdg-//g')-osmo-epdg"
exit $?
